behaviors:
  CarBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64 
      buffer_size: 12000 
      learning_rate: 0.00005
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 32 
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 20000
    summary_freq: 2000
    threaded: true
